# Relative path(s) to your source files
source: src/css

# Relative path where you want the documentation to be built
destination: styleguide

# The path that contains supporting assets for the documentation page
documentation_assets: node_modules/hologram-github-theme

# Category that will be used as the index.html (optional)
index: styleguide

# A list of relative paths to folders containing any dependencies to copy
dependencies:
  - 'dist'

# The CSS files to be included in the styleguide
css_include:
  - 'dist/css/main.css'

# The JavaScript files to included in the styleguide
js_include:
  - 'dist/scripts/main.js'

# The global title that is displayed at the top of the pages
global_title: Styleguide
